---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-admin
  namespace: kafka-connect-poc
subjects:
  - kind: ServiceAccount
    name: {{ include "connect-k8s.serviceAccountName" . }}
    namespace: {{ .Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: connector-operator
  apiGroup: ""