---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: connector-operator
rules:
  - apiGroups:
      - ""
    resources:
      - deployments
      - services
      - configmaps
      - pods
    verbs:
      - '*'
  - apiGroups:
      - "apps"
    resources:
      - services
      - configmaps
      - statefulsets
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - "io.confluent.csid"
    resources:
      - kafkaconnectors
      - kafkaconnectors/status
    verbs:
      - '*'
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - '*'